[theme]

base="light"

primaryColor= "#FF6C00"       

secondaryBackgroundColor="#FBF6F2"

textColor="#505050"          

font="sans serif"

baseRadius="2rem"        

borderColor= "#FFA366"   

showSidebarBorder = true

chartCategoricalColors = [
							  
				
				    "#E58606",  # Orange
				    "#5D69B1",  # Indigo
				    "#52BCA3",  # Teal
				    "#99C945",  # Lime Green
				    "#CC61B0",  # Magenta
				    "#24796C",  # Dark Teal
				    "#DAA51B",  # Mustard Yellow
				    "#2F8AC4",  # Blue
				    "#764E9F",  # Purple
				    "#ED645A",  # Coral Red
				    "#CC3A8E",  # Pink
				    "#A5AA99"   # Grey
				]			

showWidgetBorder = true

[server]

runOnSave = true
